apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: taskrun-workspace
spec:
  workspaces:
    - name: myworkspace
      persistentVolumeClaim:
        claimName: mypvc
  taskRef:
     name: task-workspace
