apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-workspace
spec:
  steps:
    - name: step1
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        touch /dados/file-$(date "+%Y.%m.%d-%H.%M.%S")
        ls -l /dados
        echo "Finalizado"
  workspaces:
    - name: myworkspace
      optional: true
      description: The folder where we write the message to
      mountPath: /dados