apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: workspace-task1
spec:
  steps:
    - name: step1
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Execunto o Task1-Step1"
        echo "Ola Mundo!!!" > $(workspaces.task-ws.path)/message
        echo "Finalizado"
  workspaces:
    - name: task-ws
      description: The folder where we write the message to
      mountPath: /mnt/data        