apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: resource-task1
spec:
  resources:
    inputs:
    - name: source
      type: git
  steps:
    - name: step1
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Execunto o Step1"
        ls -l /workspace/source
        echo "Finalizado"