apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-onerror-failure
spec:
  steps:
    - name: step1
      image: centos
      onError: continue 
      script: |
        #!/usr/bin/env bash
        echo "Execunto o Step1"
        xpto
    - name: step2
      image: centos
      onError: stopAndFail
      script: |
        #!/usr/bin/env bash
        echo "Execunto o Step2"
        xpto2   
    - name: step3
      image: centos    
      script: |
        #!/usr/bin/env bash
        echo "Execunto o Step3"
        xpto3