apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: parameters-task
spec:
  params:
    - name: runtime
      type: string
      description: Runtime para build
  steps:
    - name: step1
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Execunto o Task1-Step1"
        echo "Runtime Definido:" $(params.runtime)
        echo "Finalizado"